### ISSUE TITLE
No module named pygments

### ISSUE THREAD

**Issue by neeraj9** [ikatson/docker-reviewboard#26]
Commands:

```
git clone https://github.com/ikatson/docker-reviewboard
cd docker-reviewboard
make build
make run
```
The following errors persists (even when I update Dockerfile to install python-pygments or use pip to install it. I suspect that something else is broken.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 45, in load_middleware
    mw_class = import_by_path(middleware_path)
  File "/usr/lib/python2.7/site-packages/django/utils/module_loading.py", line 26, in import_by_path
    sys.exc_info()[2])
  File "/usr/lib/python2.7/site-packages/django/utils/module_loading.py", line 21, in import_by_path
    module = import_module(module_path)
  File "/usr/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/reviewboard/admin/middleware.py", line 19, in <module>
    from reviewboard.admin.siteconfig import load_site_config
  File "/usr/lib/python2.7/site-packages/reviewboard/admin/siteconfig.py", line 48, in <module>
    from reviewboard.accounts.backends import get_registered_auth_backend
  File "/usr/lib/python2.7/site-packages/reviewboard/accounts/backends.py", line 31, in <module>
    from reviewboard.accounts.models import LocalSiteProfile
  File "/usr/lib/python2.7/site-packages/reviewboard/accounts/models.py", line 19, in <module>
    from reviewboard.reviews.models import Group, ReviewRequest
  File "/usr/lib/python2.7/site-packages/reviewboard/reviews/models/__init__.py", line 6, in <module>
    from reviewboard.reviews.models.file_attachment_comment import \
  File "/usr/lib/python2.7/site-packages/reviewboard/reviews/models/file_attachment_comment.py", line 9, in <module>
    from reviewboard.attachments.models import FileAttachment
  File "/usr/lib/python2.7/site-packages/reviewboard/attachments/models.py", line 15, in <module>
    from reviewboard.attachments.mimetypes import MimetypeHandler
  File "/usr/lib/python2.7/site-packages/reviewboard/attachments/mimetypes.py", line 13, in <module>
    from pygments import highlight
django.core.exceptions.ImproperlyConfigured: Error importing module reviewboard.admin.middleware: "No module named pygments"
[pid: 28|app: 0|req: 1/1] 172.18.0.1 () {38 vars in 656 bytes} [Fri Sep 29 04:08:32 2017] GET / => generated 0 bytes in 292 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)

```

**Comment by eliocapelati** [comment]
I am exactly with the **same** problem

**Comment by mzhumakhanov** [comment]
Hi, 
And I had the same problem. Stopped struggling with it.

**Comment by ikatson** [comment]
Sorry, everyone, I don't have much time these days to look into it. Pull requests welcome.

**Comment by ikatson** [comment]
Thanks @piyusgupta

**Comment by Briffou** [comment]
I still have this issue with last commit of @piyusgupta, adding python-pygments in yum install solve the problem for me.

**Comment by ikatson** [comment]
@Briffou thanks for the report. FIxed it myself this time, and confirmed it's working.
