### ISSUE TITLE
failed on centos7 64bit, 

### ISSUE THREAD

**Issue by wangrocky** [ikatson/docker-reviewboard#34]
docker run -it --link rb-postgres:pg --link rb-memcached:memcached --volumes-from rb-data -p 8000:8000 ikatson/reviewboard
[uWSGI] getting INI configuration from /uwsgi.ini
[uwsgi-static] added mapping for /static => /var/www/reviewboard/htdocs/static
[uwsgi-static] added mapping for /media => /var/www/reviewboard/htdocs/media
[uwsgi-static] added mapping for /errordocs => /var/www/reviewboard/htdocs/errordocs
*** Starting uWSGI 2.0.15 (64bit) on [Mon Mar 19 17:11:05 2018] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-11) on 19 May 2017 14:33:49
os: Linux-3.10.0-693.17.1.el7.x86_64 #1 SMP Thu Jan 25 20:13:58 UTC 2018
nodename: 72327e7d271f
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /
detected binary path: /usr/sbin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 1048576
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
building mime-types dictionary from file /etc/mime.types...1060 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on :8000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:33740 (port auto-assigned) fd 3
Python version: 2.7.5 (default, Aug  4 2017, 00:39:18)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
Python main interpreter initialized at 0x1d4fa90
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145536 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
**failed to open python file /var/www/reviewboard/conf/settings_local.py**

i don't know what's going on..

**Comment by liugh-dev** [comment]
I have some similar:

root@xubuntu-22:~/docker-reviewboard# docker-compose logs -f --tail=100 reviewboard
Attaching to docker-reviewboard_reviewboard_1
reviewboard_1  |     if self.print_missing_dependencies():
reviewboard_1  |   File "/opt/venv/local/lib/python2.7/site-packages/reviewboard/cmdline/rbsite.py", line 1351, in print_missing_dependencies
reviewboard_1  |     fatal, missing_dep_groups = Dependencies.get_missing()
reviewboard_1  |   File "/opt/venv/local/lib/python2.7/site-packages/reviewboard/cmdline/rbsite.py", line 112, in get_missing
reviewboard_1  |     if not cls.has_modules(modules):
reviewboard_1  |   File "/opt/venv/local/lib/python2.7/site-packages/reviewboard/cmdline/rbsite.py", line 135, in has_modules
reviewboard_1  |     __import__(name)
reviewboard_1  |   File "/opt/venv/local/lib/python2.7/site-packages/memcache.py", line 374
reviewboard_1  |     def quit_all(self) -> None:
reviewboard_1  |                        ^
reviewboard_1  | SyntaxError: invalid syntax
reviewboard_1  | 
reviewboard_1  | ERROR: Unable to import settings_local.py: No module named
reviewboard_1  |        settings_local
reviewboard_1  | Traceback (most recent call last):
reviewboard_1  |   File "/opt/venv/bin/rb-site", line 8, in <module>
reviewboard_1  |     sys.exit(main())
reviewboard_1  |   File "/opt/venv/local/lib/python2.7/site-packages/reviewboard/cmdline/rbsite.py", line 1972, in main
reviewboard_1  |     command.run()
reviewboard_1  |   File "/opt/venv/local/lib/python2.7/site-packages/reviewboard/cmdline/rbsite.py", line 1743, in run
reviewboard_1  |     diff_dedup_needed = site.get_diff_dedup_needed()
reviewboard_1  |   File "/opt/venv/local/lib/python2.7/site-packages/reviewboard/cmdline/rbsite.py", line 515, in get_diff_dedup_needed
reviewboard_1  |     from reviewboard.diffviewer.models import FileDiff
reviewboard_1  |   File "/opt/venv/local/lib/python2.7/site-packages/reviewboard/diffviewer/models.py", line 6, in <module>
reviewboard_1  |     from django.db import models
reviewboard_1  |   File "/opt/venv/local/lib/python2.7/site-packages/django/db/models/__init__.py", line 5, in <module>
reviewboard_1  |     from django.db.models.query import Q
reviewboard_1  |   File "/opt/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 17, in <module>
reviewboard_1  |     from django.db.models.deletion import Collector
reviewboard_1  |   File "/opt/venv/local/lib/python2.7/site-packages/django/db/models/deletion.py", line 4, in <module>
reviewboard_1  |     from django.db.models import signals, sql
reviewboard_1  |   File "/opt/venv/local/lib/python2.7/site-packages/django/db/models/sql/__init__.py", line 4, in <module>
reviewboard_1  |     from django.db.models.sql.subqueries import *
reviewboard_1  |   File "/opt/venv/local/lib/python2.7/site-packages/django/db/models/sql/subqueries.py", line 12, in <module>
reviewboard_1  |     from django.db.models.sql.query import Query
reviewboard_1  |   File "/opt/venv/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 22, in <module>
reviewboard_1  |     from django.db.models.sql import aggregates as base_aggregates_module
reviewboard_1  |   File "/opt/venv/local/lib/python2.7/site-packages/django/db/models/sql/aggregates.py", line 9, in <module>
reviewboard_1  |     ordinal_aggregate_field = IntegerField()
reviewboard_1  |   File "/opt/venv/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 116, in __init__
reviewboard_1  |     self.db_tablespace = db_tablespace or settings.DEFAULT_INDEX_TABLESPACE
reviewboard_1  |   File "/opt/venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
reviewboard_1  |     self._setup(name)
reviewboard_1  |   File "/opt/venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
reviewboard_1  |     self._wrapped = Settings(settings_module)
reviewboard_1  |   File "/opt/venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 128, in __init__
reviewboard_1  |     mod = importlib.import_module(self.SETTINGS_MODULE)
reviewboard_1  |   File "/opt/venv/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
reviewboard_1  |     __import__(name)
reviewboard_1  |   File "/opt/venv/local/lib/python2.7/site-packages/reviewboard/settings.py", line 321, in <module>
reviewboard_1  |     for db_info in DATABASES.values():
reviewboard_1  | NameError: name 'DATABASES' is not defined
reviewboard_1  | ReviewBoard upgrade detected, performing rb-site upgrade
reviewboard_1  | Traceback (most recent call last):
reviewboard_1  |   File "/upgrade-site.py", line 26, in <module>
reviewboard_1  |     main(*sys.argv[1:])
reviewboard_1  |   File "/upgrade-site.py", line 20, in main
reviewboard_1  |     subprocess.check_call(["rb-site", "upgrade", site_folder])
reviewboard_1  |   File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
reviewboard_1  |     raise CalledProcessError(retcode, cmd)
reviewboard_1  | subprocess.CalledProcessError: Command '['rb-site', 'upgrade', '/var/www/reviewboard']' returned non-zero exit status 1
reviewboard_1  | [uWSGI] getting INI configuration from /uwsgi.ini
reviewboard_1  | [uwsgi-static] added mapping for /static => /var/www/reviewboard/htdocs/static
reviewboard_1  | [uwsgi-static] added mapping for /media => /var/www/reviewboard/htdocs/media
reviewboard_1  | [uwsgi-static] added mapping for /errordocs => /var/www/reviewboard/htdocs/errordocs
reviewboard_1  | *** Starting uWSGI 2.0.15-debian (64bit) on [Mon Apr  8 05:39:40 2024] ***
reviewboard_1  | compiled with version: 7.5.0 on 26 August 2021 18:40:50
reviewboard_1  | os: Linux-5.15.0-101-generic #111-Ubuntu SMP Tue Mar 5 20:16:58 UTC 2024
reviewboard_1  | nodename: 97c4942aae71
reviewboard_1  | machine: x86_64
reviewboard_1  | clock source: unix
reviewboard_1  | pcre jit disabled
reviewboard_1  | detected number of CPU cores: 4
reviewboard_1  | current working directory: /
reviewboard_1  | detected binary path: /usr/bin/uwsgi-core
reviewboard_1  | dropping root privileges as early as possible
reviewboard_1  | uWSGI running as root, you can use --uid/--gid/--chroot options
reviewboard_1  | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
reviewboard_1  | your memory page size is 4096 bytes
reviewboard_1  | detected max file descriptor number: 1048576
reviewboard_1  | building mime-types dictionary from file /etc/mime.types...554 entry found
reviewboard_1  | lock engine: pthread robust mutexes
reviewboard_1  | thunder lock: disabled (you can enable it with --thunder-lock)
reviewboard_1  | uWSGI http bound on :8000 fd 4
reviewboard_1  | uwsgi socket 0 bound to TCP address 127.0.0.1:34015 (port auto-assigned) fd 3
reviewboard_1  | dropping root privileges after socket binding
reviewboard_1  | uWSGI running as root, you can use --uid/--gid/--chroot options
reviewboard_1  | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
reviewboard_1  | Python version: 2.7.17 (default, Mar  8 2023, 18:40:28)  [GCC 7.5.0]
reviewboard_1  | Set PythonHome to /opt/venv/
reviewboard_1  | Python main interpreter initialized at 0x55a3bf5d0bd0
reviewboard_1  | dropping root privileges after plugin initialization
reviewboard_1  | uWSGI running as root, you can use --uid/--gid/--chroot options
reviewboard_1  | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
reviewboard_1  | python threads support enabled
reviewboard_1  | your server socket listen backlog is limited to 100 connections
reviewboard_1  | your mercy for graceful operations on workers is 60 seconds
reviewboard_1  | mapped 384320 bytes (375 KB) for 4 cores
reviewboard_1  | *** Operational MODE: preforking ***
**reviewboard_1  | failed to open python file /var/www/reviewboard/conf/settings_local.py**
docker-reviewboard_reviewboard_1 exited with code 1
